apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: mlops-container
        image: 116981779709.dkr.ecr.ap-south-1.amazonaws.com/mlops-project-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
